name: "Update Flake Deps"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-lock:
    name: lock
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Update flake deps
      working-directory: nix
      run: nix flake update

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update flake.lock"
        branch: master

  update-vendor-sha:
    name: vendor-sha
    runs-on: ubuntu-latest
    needs: update-lock
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Update packwiz version
      working-directory: nix
      run: nix run nixpkgs#nix-prefetch ./prefetcher.nix 2>/dev/null | tee ./vendor-sha256

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update packwiz vendorSha256"
        branch: master

